config/routes.rb
EmpApp::Application.routes.draw do
  resources :project_requests

  resources :employees

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  attr_accessible :department, :employee_email, :employee_name, 
  :location, :years_with_company, :manager, :position, :group
  has_many :project_requests
end

app/models/project_request.rb
class ProjectRequest < ActiveRecord::Base
  attr_accessible :employee_id, :project_help
  belongs_to :employee
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @employees }
    end
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
    @employee = Employee.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @employee }
    end
  end

  # GET /employees/new
  # GET /employees/new.json
  def new
    @employee = Employee.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @employee }
    end
  end

  # GET /employees/1/edit
  def edit
    @employee = Employee.find(params[:id])
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(params[:employee])

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render json: @employee, status: :created, location: @employee }
      else
        format.html { render action: "new" }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /employees/1
  # PUT /employees/1.json
  def update
    @employee = Employee.find(params[:id])

    respond_to do |format|
      if @employee.update_attributes(params[:employee])
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee = Employee.find(params[:id])
    @employee.destroy

    respond_to do |format|
      format.html { redirect_to employees_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/project_requests_controller.rb
class ProjectRequestsController < ApplicationController
  # GET /project_requests
  # GET /project_requests.json
  def index
    @project_requests = ProjectRequest.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @project_requests }
    end
  end

  # GET /project_requests/1
  # GET /project_requests/1.json
  def show
    @project_request = ProjectRequest.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project_request }
    end
  end

  # GET /project_requests/new
  # GET /project_requests/new.json
  def new
    @project_request = ProjectRequest.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project_request }
    end
  end

  # GET /project_requests/1/edit
  def edit
    @project_request = ProjectRequest.find(params[:id])
  end

  # POST /project_requests
  # POST /project_requests.json
  def create
    @project_request = ProjectRequest.new(params[:project_request])

    respond_to do |format|
      if @project_request.save
        format.html { redirect_to @project_request, notice: 'Project request was successfully created.' }
        format.json { render json: @project_request, status: :created, location: @project_request }
      else
        format.html { render action: "new" }
        format.json { render json: @project_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /project_requests/1
  # PUT /project_requests/1.json
  def update
    @project_request = ProjectRequest.find(params[:id])

    respond_to do |format|
      if @project_request.update_attributes(params[:project_request])
        format.html { redirect_to @project_request, notice: 'Project request was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /project_requests/1
  # DELETE /project_requests/1.json
  def destroy
    @project_request = ProjectRequest.find(params[:id])
    @project_request.destroy

    respond_to do |format|
      format.html { redirect_to project_requests_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/project_requests_helper.rb
module ProjectRequestsHelper
end

app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :employee_name %><br />
    <%= f.text_field :employee_name %>
  </div>
  <div class="field">
    <%= f.label :employee_email %><br />
    <%= f.text_field :employee_email %>
  </div>

  <div class="field">
    <%= f.label :years_with_company %><br />
    <%= f.text_field :years_with_company %>
  </div>

  <div class="field">
    <%= f.label :manager %><br />
    <%= f.text_field :manager %>
  </div>

  <div class="field">
    <%= f.label :position %><br />
    <%= f.text_field :position %>
  </div>

  <div class="field">
    <%= f.label :department %><br />
    <%= f.text_field :department %>
  </div>

  <div class="field">
    <%= f.label :group %><br />
    <%= f.text_field :group %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing employee</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<h1>Listing employees</h1>

<table>
  <tr>
    <th>Employee name</th>
    <th>Employee email</th>
    <th>Years with Company</th>
    <th>Manager/Lead</th>
    <th>Position</th>
    <th>Department</th>
    <th>Group</th>
    <th>Location</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @employees.each do |employee| %>
  <tr>
    <td><%= employee.employee_name %></td>
    <td><%= employee.employee_email %></td>
    <td><%= employee.years_with_company %></td>
    <td><%= employee.manager %></td>
    <td><%= employee.position %></td>
    <td><%= employee.department %></td>
    <td><%= employee.group %></td>
    <td><%= employee.location %></td>
    <td><%= link_to 'Show', employee %></td>
    <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
    <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Employee', new_employee_path %>

app/views/employees/new.html.erb
<h1>New employee</h1>

<%= render 'form' %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Employee name:</b>
  <%= @employee.employee_name %>
</p>

<p>
  <b>Employee email:</b>
  <%= @employee.employee_email %>
</p>

<p>
  <b>Years with Company:</b>
  <%= @employee.years_with_company %>
</p>

<p>
  <b>Manager/Lead:</b>
  <%= @employee.manager %>
</p>

<p>
  <b>Position:</b>
  <%= @employee.position %>
</p>

<p>
  <b>Department:</b>
  <%= @employee.department %>
</p>

<p>
  <b>Group:</b>
  <%= @employee.group %>
</p>
<p>
  <b>Location:</b>
  <%= @employee.location %>
</p>




<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EmpApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/project_requests/_form.html.erb
<%= form_for(@project_request) do |f| %>
  <% if @project_request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project_request.errors.count, "error") %> prohibited this project_request from being saved:</h2>

      <ul>
      <% @project_request.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :project_help %><br />
    <%= f.text_field :project_help %>
  </div>
  <div class="field">
    <%= f.label :employee_id %><br />
    <%= f.number_field :employee_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/project_requests/edit.html.erb
<h1>Editing project_request</h1>

<%= render 'form' %>

<%= link_to 'Show', @project_request %> |
<%= link_to 'Back', project_requests_path %>

app/views/project_requests/index.html.erb
<h1>Listing project_requests</h1>

<table>
  <tr>
    <th>Project help</th>
    <th>Employee</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @project_requests.each do |project_request| %>
  <tr>
    <td><%= project_request.project_help %></td>
    <td><%= project_request.employee_id %></td>
    <td><%= link_to 'Show', project_request %></td>
    <td><%= link_to 'Edit', edit_project_request_path(project_request) %></td>
    <td><%= link_to 'Destroy', project_request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Project request', new_project_request_path %>

app/views/project_requests/new.html.erb
<h1>New project_request</h1>

<%= render 'form' %>

<%= link_to 'Back', project_requests_path %>

app/views/project_requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Project help:</b>
  <%= @project_request.project_help %>
</p>

<p>
  <b>Employee:</b>
  <%= @project_request.employee_id %>
</p>


<%= link_to 'Edit', edit_project_request_path(@project_request) %> |
<%= link_to 'Back', project_requests_path %>